/*
Resend

Resend is the email platform for developers.

The version of the OpenAPI document: 1.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { AxiosRequestConfig } from "axios";
import {
  ApiKeysApi,
  AudiencesApi,
  ContactsApi,
  DomainsApi,
  EmailsApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { ResendCustom } from "./client-custom";

export class Resend extends ResendCustom {
  readonly apiKeys: ApiKeysApi;
  readonly audiences: AudiencesApi;
  readonly contacts: ContactsApi;
  readonly domains: DomainsApi;
  readonly emails: EmailsApi;

  constructor(configurationParameters: ConfigurationParameters) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.apiKeys = new ApiKeysApi(configuration);
    this.audiences = new AudiencesApi(configuration);
    this.contacts = new ContactsApi(configuration);
    this.domains = new DomainsApi(configuration);
    this.emails = new EmailsApi(configuration);
  }

}
