/*
Resend

Resend is the email platform for developers.

The version of the OpenAPI document: 1.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ApiKey
 */
export interface ApiKey {
    /**
     * The ID of the API key.
     * @type {string}
     * @memberof ApiKey
     */
    'id'?: string;
    /**
     * The name of the API key.
     * @type {string}
     * @memberof ApiKey
     */
    'name'?: string;
    /**
     * The date and time the API key was created.
     * @type {string}
     * @memberof ApiKey
     */
    'created_at'?: string;
}

