/*
Resend

Resend is the email platform for developers.

The version of the OpenAPI document: 1.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Attachment
 */
export interface Attachment {
    /**
     * Content of an attached file.
     * @type {Uint8Array | File | buffer.File}
     * @memberof Attachment
     */
    'content'?: Uint8Array | File | buffer.File;
    /**
     * Name of attached file.
     * @type {string}
     * @memberof Attachment
     */
    'filename'?: string;
    /**
     * Path where the attachment file is hosted
     * @type {string}
     * @memberof Attachment
     */
    'path'?: string;
}

