/*
Resend

Resend is the email platform for developers.

The version of the OpenAPI document: 1.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CreateBatchEmailsResponseDataInner
 */
export interface CreateBatchEmailsResponseDataInner {
    /**
     * The ID of the sent email.
     * @type {string}
     * @memberof CreateBatchEmailsResponseDataInner
     */
    'id'?: string;
}

