/*
Resend

Resend is the email platform for developers.

The version of the OpenAPI document: 1.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CreateApiKeyResponse
 */
export interface CreateApiKeyResponse {
    /**
     * The ID of the API key.
     * @type {string}
     * @memberof CreateApiKeyResponse
     */
    'id'?: string;
    /**
     * The token of the API key.
     * @type {string}
     * @memberof CreateApiKeyResponse
     */
    'token'?: string;
}

