/*
Resend

Resend is the email platform for developers.

The version of the OpenAPI document: 1.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CreateApiKeyRequest
 */
export interface CreateApiKeyRequest {
    /**
     * The API key name.
     * @type {string}
     * @memberof CreateApiKeyRequest
     */
    'name': string;
    /**
     * The API key can have full access to Resend’s API or be only restricted to send emails. * full_access - Can create, delete, get, and update any resource. * sending_access - Can only send emails.
     * @type {string}
     * @memberof CreateApiKeyRequest
     */
    'permission'?: CreateApiKeyRequestPermissionEnum;
    /**
     * Restrict an API key to send emails only from a specific domain. Only used when the permission is sending_acces.
     * @type {string}
     * @memberof CreateApiKeyRequest
     */
    'domain_id'?: string;
}

type CreateApiKeyRequestPermissionEnum = 'full_access' | 'sending_access'


