/*
Resend

Resend is the email platform for developers.

The version of the OpenAPI document: 1.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CreateContactOptions
 */
export interface CreateContactOptions {
    /**
     * Email address of the contact.
     * @type {string}
     * @memberof CreateContactOptions
     */
    'email': string;
    /**
     * First name of the contact.
     * @type {string}
     * @memberof CreateContactOptions
     */
    'first_name'?: string;
    /**
     * Last name of the contact.
     * @type {string}
     * @memberof CreateContactOptions
     */
    'last_name'?: string;
    /**
     * Indicates if the contact is unsubscribed.
     * @type {boolean}
     * @memberof CreateContactOptions
     */
    'unsubscribed'?: boolean;
    /**
     * Unique identifier of the audience to which the contact belongs.
     * @type {string}
     * @memberof CreateContactOptions
     */
    'audience_id'?: string;
}

