/*
Resend

Resend is the email platform for developers.

The version of the OpenAPI document: 1.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CreateAudienceResponseSuccess
 */
export interface CreateAudienceResponseSuccess {
    /**
     * The ID of the audience.
     * @type {string}
     * @memberof CreateAudienceResponseSuccess
     */
    'id'?: string;
    /**
     * The object of the audience.
     * @type {string}
     * @memberof CreateAudienceResponseSuccess
     */
    'object'?: string;
    /**
     * The name of the audience.
     * @type {string}
     * @memberof CreateAudienceResponseSuccess
     */
    'name'?: string;
}

