/*
Resend

Resend is the email platform for developers.

The version of the OpenAPI document: 1.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CreateBatchEmailsResponseDataInner } from './create-batch-emails-response-data-inner';

/**
 * 
 * @export
 * @interface CreateBatchEmailsResponse
 */
export interface CreateBatchEmailsResponse {
    /**
     * 
     * @type {Array<CreateBatchEmailsResponseDataInner>}
     * @memberof CreateBatchEmailsResponse
     */
    'data'?: Array<CreateBatchEmailsResponseDataInner>;
}

