/*
Resend

Resend is the email platform for developers.

The version of the OpenAPI document: 1.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CreateAudienceOptions
 */
export interface CreateAudienceOptions {
    /**
     * The name of the audience you want to create.
     * @type {string}
     * @memberof CreateAudienceOptions
     */
    'name': string;
}

