/*
Resend

Resend is the email platform for developers.

The version of the OpenAPI document: 1.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface DeleteDomainResponse
 */
export interface DeleteDomainResponse {
    /**
     * The type of object.
     * @type {string}
     * @memberof DeleteDomainResponse
     */
    'object'?: string;
    /**
     * The ID of the domain.
     * @type {string}
     * @memberof DeleteDomainResponse
     */
    'id'?: string;
    /**
     * Indicates whether the domain was deleted successfully.
     * @type {boolean}
     * @memberof DeleteDomainResponse
     */
    'deleted'?: boolean;
}

