/*
Resend

Resend is the email platform for developers.

The version of the OpenAPI document: 1.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface DomainRecord
 */
export interface DomainRecord {
    /**
     * The type of record.
     * @type {string}
     * @memberof DomainRecord
     */
    'record'?: string;
    /**
     * The name of the record.
     * @type {string}
     * @memberof DomainRecord
     */
    'name'?: string;
    /**
     * The type of record.
     * @type {string}
     * @memberof DomainRecord
     */
    'type'?: string;
    /**
     * The time to live for the record.
     * @type {string}
     * @memberof DomainRecord
     */
    'ttl'?: string;
    /**
     * The status of the record.
     * @type {string}
     * @memberof DomainRecord
     */
    'status'?: string;
    /**
     * The value of the record.
     * @type {string}
     * @memberof DomainRecord
     */
    'value'?: string;
    /**
     * The priority of the record.
     * @type {number}
     * @memberof DomainRecord
     */
    'priority'?: number;
}

