/*
Resend

Resend is the email platform for developers.

The version of the OpenAPI document: 1.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DomainRecord } from './domain-record';

/**
 * 
 * @export
 * @interface Domain
 */
export interface Domain {
    /**
     * The type of object.
     * @type {string}
     * @memberof Domain
     */
    'object'?: string;
    /**
     * The ID of the domain.
     * @type {string}
     * @memberof Domain
     */
    'id'?: string;
    /**
     * The name of the domain.
     * @type {string}
     * @memberof Domain
     */
    'name'?: string;
    /**
     * The status of the domain.
     * @type {string}
     * @memberof Domain
     */
    'status'?: string;
    /**
     * The date and time the domain was created.
     * @type {string}
     * @memberof Domain
     */
    'created_at'?: string;
    /**
     * The region where the domain is hosted.
     * @type {string}
     * @memberof Domain
     */
    'region'?: string;
    /**
     * 
     * @type {Array<DomainRecord>}
     * @memberof Domain
     */
    'records'?: Array<DomainRecord>;
}

