/*
Resend

Resend is the email platform for developers.

The version of the OpenAPI document: 1.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Email
 */
export interface Email {
    /**
     * The type of object.
     * @type {string}
     * @memberof Email
     */
    'object'?: string;
    /**
     * The ID of the email.
     * @type {string}
     * @memberof Email
     */
    'id'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof Email
     */
    'to'?: Array<string>;
    /**
     * The email address of the sender.
     * @type {string}
     * @memberof Email
     */
    'from'?: string;
    /**
     * The date and time the email was created.
     * @type {string}
     * @memberof Email
     */
    'created_at'?: string;
    /**
     * The subject line of the email.
     * @type {string}
     * @memberof Email
     */
    'subject'?: string;
    /**
     * The HTML body of the email.
     * @type {string}
     * @memberof Email
     */
    'html'?: string;
    /**
     * The plain text body of the email.
     * @type {string}
     * @memberof Email
     */
    'text'?: string;
    /**
     * The email addresses of the blind carbon copy recipients.
     * @type {Array<string>}
     * @memberof Email
     */
    'bcc'?: Array<string>;
    /**
     * The email addresses of the carbon copy recipients.
     * @type {Array<string>}
     * @memberof Email
     */
    'cc'?: Array<string>;
    /**
     * The email addresses to which replies should be sent.
     * @type {Array<string>}
     * @memberof Email
     */
    'reply_to'?: Array<string>;
    /**
     * The status of the email.
     * @type {string}
     * @memberof Email
     */
    'last_event'?: string;
}

