/*
Resend

Resend is the email platform for developers.

The version of the OpenAPI document: 1.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ListAudiencesResponseSuccessDataInner } from './list-audiences-response-success-data-inner';

/**
 * 
 * @export
 * @interface ListAudiencesResponseSuccess
 */
export interface ListAudiencesResponseSuccess {
    /**
     * Type of the response object.
     * @type {string}
     * @memberof ListAudiencesResponseSuccess
     */
    'object'?: string;
    /**
     * Array containing audience information.
     * @type {Array<ListAudiencesResponseSuccessDataInner>}
     * @memberof ListAudiencesResponseSuccess
     */
    'data'?: Array<ListAudiencesResponseSuccessDataInner>;
}

