/*
Resend

Resend is the email platform for developers.

The version of the OpenAPI document: 1.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ListContactsResponseSuccessDataInner
 */
export interface ListContactsResponseSuccessDataInner {
    /**
     * Unique identifier for the contact.
     * @type {string}
     * @memberof ListContactsResponseSuccessDataInner
     */
    'id'?: string;
    /**
     * Email address of the contact.
     * @type {string}
     * @memberof ListContactsResponseSuccessDataInner
     */
    'email'?: string;
    /**
     * First name of the contact.
     * @type {string}
     * @memberof ListContactsResponseSuccessDataInner
     */
    'first_name'?: string;
    /**
     * Last name of the contact.
     * @type {string}
     * @memberof ListContactsResponseSuccessDataInner
     */
    'last_name'?: string;
    /**
     * Timestamp indicating when the contact was created.
     * @type {string}
     * @memberof ListContactsResponseSuccessDataInner
     */
    'created_at'?: string;
    /**
     * Indicates if the contact is unsubscribed.
     * @type {boolean}
     * @memberof ListContactsResponseSuccessDataInner
     */
    'unsubscribed'?: boolean;
}

