/*
Resend

Resend is the email platform for developers.

The version of the OpenAPI document: 1.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ListAudiencesResponseSuccessDataInner
 */
export interface ListAudiencesResponseSuccessDataInner {
    /**
     * Unique identifier for the audience.
     * @type {string}
     * @memberof ListAudiencesResponseSuccessDataInner
     */
    'id'?: string;
    /**
     * Name of the audience.
     * @type {string}
     * @memberof ListAudiencesResponseSuccessDataInner
     */
    'name'?: string;
    /**
     * Timestamp indicating when the audience was created.
     * @type {string}
     * @memberof ListAudiencesResponseSuccessDataInner
     */
    'created_at'?: string;
}

