/*
Resend

Resend is the email platform for developers.

The version of the OpenAPI document: 1.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ListDomainsItem
 */
export interface ListDomainsItem {
    /**
     * The ID of the domain.
     * @type {string}
     * @memberof ListDomainsItem
     */
    'id'?: string;
    /**
     * The name of the domain.
     * @type {string}
     * @memberof ListDomainsItem
     */
    'name'?: string;
    /**
     * The status of the domain.
     * @type {string}
     * @memberof ListDomainsItem
     */
    'status'?: string;
    /**
     * The date and time the domain was created.
     * @type {string}
     * @memberof ListDomainsItem
     */
    'created_at'?: string;
    /**
     * The region where the domain is hosted.
     * @type {string}
     * @memberof ListDomainsItem
     */
    'region'?: string;
}

