/*
Resend

Resend is the email platform for developers.

The version of the OpenAPI document: 1.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ListDomainsItem } from './list-domains-item';

/**
 * 
 * @export
 * @interface ListDomainsResponse
 */
export interface ListDomainsResponse {
    /**
     * 
     * @type {Array<ListDomainsItem>}
     * @memberof ListDomainsResponse
     */
    'data'?: Array<ListDomainsItem>;
}

