/*
Resend

Resend is the email platform for developers.

The version of the OpenAPI document: 1.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ApiKey } from './api-key';

/**
 * 
 * @export
 * @interface ListApiKeysResponse
 */
export interface ListApiKeysResponse {
    /**
     * 
     * @type {Array<ApiKey>}
     * @memberof ListApiKeysResponse
     */
    'data'?: Array<ApiKey>;
}

