/*
Resend

Resend is the email platform for developers.

The version of the OpenAPI document: 1.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ListContactsResponseSuccessDataInner } from './list-contacts-response-success-data-inner';

/**
 * 
 * @export
 * @interface ListContactsResponseSuccess
 */
export interface ListContactsResponseSuccess {
    /**
     * Type of the response object.
     * @type {string}
     * @memberof ListContactsResponseSuccess
     */
    'object'?: string;
    /**
     * Array containing contact information.
     * @type {Array<ListContactsResponseSuccessDataInner>}
     * @memberof ListContactsResponseSuccess
     */
    'data'?: Array<ListContactsResponseSuccessDataInner>;
}

