/*
Resend

Resend is the email platform for developers.

The version of the OpenAPI document: 1.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface RemoveContactResponseSuccess
 */
export interface RemoveContactResponseSuccess {
    /**
     * Type of the response object.
     * @type {string}
     * @memberof RemoveContactResponseSuccess
     */
    'object'?: string;
    /**
     * Unique identifier for the removed contact.
     * @type {string}
     * @memberof RemoveContactResponseSuccess
     */
    'id'?: string;
    /**
     * Indicates whether the contact was successfully deleted.
     * @type {boolean}
     * @memberof RemoveContactResponseSuccess
     */
    'deleted'?: boolean;
}

