/*
Resend

Resend is the email platform for developers.

The version of the OpenAPI document: 1.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface RemoveAudienceResponseSuccess
 */
export interface RemoveAudienceResponseSuccess {
    /**
     * The ID of the audience.
     * @type {string}
     * @memberof RemoveAudienceResponseSuccess
     */
    'id'?: string;
    /**
     * The object of the audience.
     * @type {string}
     * @memberof RemoveAudienceResponseSuccess
     */
    'object'?: string;
    /**
     * The deleted attribute indicates that the corresponding audience has been deleted.
     * @type {boolean}
     * @memberof RemoveAudienceResponseSuccess
     */
    'deleted'?: boolean;
}

