/*
Resend

Resend is the email platform for developers.

The version of the OpenAPI document: 1.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Attachment } from './attachment';
import { Tag } from './tag';

/**
 * 
 * @export
 * @interface SendEmailRequest
 */
export interface SendEmailRequest {
    /**
     * 
     * @type {Array<Tag>}
     * @memberof SendEmailRequest
     */
    'tags'?: Array<Tag>;
    /**
     * Sender email address. To include a friendly name, use the format \"Your Name <sender@domain.com>\".
     * @type {string}
     * @memberof SendEmailRequest
     */
    'from': string;
    /**
     * 
     * @type {Array<string>}
     * @memberof SendEmailRequest
     */
    'to': Array<string>;
    /**
     * Email subject.
     * @type {string}
     * @memberof SendEmailRequest
     */
    'subject': string;
    /**
     * Bcc recipient email address. For multiple addresses, send as an array of strings.
     * @type {string}
     * @memberof SendEmailRequest
     */
    'bcc'?: string;
    /**
     * Cc recipient email address. For multiple addresses, send as an array of strings.
     * @type {string}
     * @memberof SendEmailRequest
     */
    'cc'?: string;
    /**
     * Reply-to email address. For multiple addresses, send as an array of strings.
     * @type {string}
     * @memberof SendEmailRequest
     */
    'reply_to'?: string;
    /**
     * The HTML version of the message.
     * @type {string}
     * @memberof SendEmailRequest
     */
    'html'?: string;
    /**
     * The plain text version of the message.
     * @type {string}
     * @memberof SendEmailRequest
     */
    'text'?: string;
    /**
     * Custom headers to add to the email.
     * @type {object}
     * @memberof SendEmailRequest
     */
    'headers'?: object;
    /**
     * 
     * @type {Array<Attachment>}
     * @memberof SendEmailRequest
     */
    'attachments'?: Array<Attachment>;
}

