/*
Resend

Resend is the email platform for developers.

The version of the OpenAPI document: 1.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface UpdateDomainOptions
 */
export interface UpdateDomainOptions {
    /**
     * Enable or disable click tracking for the domain.
     * @type {boolean}
     * @memberof UpdateDomainOptions
     */
    'click_tracking'?: boolean;
    /**
     * Enable or disable open tracking for the domain.
     * @type {boolean}
     * @memberof UpdateDomainOptions
     */
    'open_tracking'?: boolean;
}

