/*
Resend

Resend is the email platform for developers.

The version of the OpenAPI document: 1.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface UpdateContactResponseSuccess
 */
export interface UpdateContactResponseSuccess {
    /**
     * Type of the response object.
     * @type {string}
     * @memberof UpdateContactResponseSuccess
     */
    'object'?: string;
    /**
     * Unique identifier for the updated contact.
     * @type {string}
     * @memberof UpdateContactResponseSuccess
     */
    'id'?: string;
}

