/*
Resend

Resend is the email platform for developers.

The version of the OpenAPI document: 1.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface UpdateContactOptions
 */
export interface UpdateContactOptions {
    /**
     * Email address of the contact.
     * @type {string}
     * @memberof UpdateContactOptions
     */
    'email'?: string;
    /**
     * First name of the contact.
     * @type {string}
     * @memberof UpdateContactOptions
     */
    'first_name'?: string;
    /**
     * Last name of the contact.
     * @type {string}
     * @memberof UpdateContactOptions
     */
    'last_name'?: string;
    /**
     * Indicates the subscription status of the contact.
     * @type {boolean}
     * @memberof UpdateContactOptions
     */
    'unsubscribed'?: boolean;
}

