/*
Resend

Resend is the email platform for developers.

The version of the OpenAPI document: 1.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface UpdateDomainResponseSuccess
 */
export interface UpdateDomainResponseSuccess {
    /**
     * The ID of the updated domain.
     * @type {string}
     * @memberof UpdateDomainResponseSuccess
     */
    'id'?: string;
    /**
     * The object type representing the updated domain.
     * @type {string}
     * @memberof UpdateDomainResponseSuccess
     */
    'object'?: string;
}

