/*
Resend

Resend is the email platform for developers.

The version of the OpenAPI document: 1.1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface VerifyDomainResponse
 */
export interface VerifyDomainResponse {
    /**
     * The type of object.
     * @type {string}
     * @memberof VerifyDomainResponse
     */
    'object'?: string;
    /**
     * The ID of the domain.
     * @type {string}
     * @memberof VerifyDomainResponse
     */
    'id'?: string;
}

